Buildroot: /media/files/Projects/Site Monster/sitemonster-1.0
Name: sitemonster
Version: 1.0
Release: 1
Summary: Site Monster is an app for site admins, which will immediately notify you when your site goes down.
License: see /usr/share/doc/sitemonster/copyright
#Distribution: Debian
Group: net

%define _binaries_in_noarch_packages_terminate_build   0
%define _rpmdir ../
%define _rpmfilename %%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.rpm
%define _unpackaged_files_terminate_build 0

%description


%files
%dir "/"
%dir "/etc/"
%dir "/etc/init.d/"
%dir "/opt/"
%dir "/opt/SiteMonster/"
"/opt/SiteMonster/LICENSE"
%dir "/opt/SiteMonster/PyQt5/"
%dir "/opt/SiteMonster/PyQt5/Qt/"
%dir "/opt/SiteMonster/PyQt5/Qt/plugins/"
%dir "/opt/SiteMonster/PyQt5/Qt/plugins/iconengines/"
"/opt/SiteMonster/PyQt5/Qt/plugins/iconengines/libqsvgicon.so"
%dir "/opt/SiteMonster/PyQt5/Qt/plugins/imageformats/"
"/opt/SiteMonster/PyQt5/Qt/plugins/imageformats/kimg_eps.so"
"/opt/SiteMonster/PyQt5/Qt/plugins/imageformats/kimg_exr.so"
"/opt/SiteMonster/PyQt5/Qt/plugins/imageformats/kimg_kra.so"
"/opt/SiteMonster/PyQt5/Qt/plugins/imageformats/kimg_ora.so"
"/opt/SiteMonster/PyQt5/Qt/plugins/imageformats/kimg_pcx.so"
"/opt/SiteMonster/PyQt5/Qt/plugins/imageformats/kimg_pic.so"
"/opt/SiteMonster/PyQt5/Qt/plugins/imageformats/kimg_psd.so"
"/opt/SiteMonster/PyQt5/Qt/plugins/imageformats/kimg_ras.so"
"/opt/SiteMonster/PyQt5/Qt/plugins/imageformats/kimg_rgb.so"
"/opt/SiteMonster/PyQt5/Qt/plugins/imageformats/kimg_tga.so"
"/opt/SiteMonster/PyQt5/Qt/plugins/imageformats/kimg_xcf.so"
"/opt/SiteMonster/PyQt5/Qt/plugins/imageformats/libqgif.so"
"/opt/SiteMonster/PyQt5/Qt/plugins/imageformats/libqicns.so"
"/opt/SiteMonster/PyQt5/Qt/plugins/imageformats/libqico.so"
"/opt/SiteMonster/PyQt5/Qt/plugins/imageformats/libqjpeg.so"
"/opt/SiteMonster/PyQt5/Qt/plugins/imageformats/libqmng.so"
"/opt/SiteMonster/PyQt5/Qt/plugins/imageformats/libqsvg.so"
"/opt/SiteMonster/PyQt5/Qt/plugins/imageformats/libqtga.so"
"/opt/SiteMonster/PyQt5/Qt/plugins/imageformats/libqtiff.so"
"/opt/SiteMonster/PyQt5/Qt/plugins/imageformats/libqwbmp.so"
"/opt/SiteMonster/PyQt5/Qt/plugins/imageformats/libqwebp.so"
%dir "/opt/SiteMonster/PyQt5/Qt/plugins/platforms/"
"/opt/SiteMonster/PyQt5/Qt/plugins/platforms/libqeglfs.so"
"/opt/SiteMonster/PyQt5/Qt/plugins/platforms/libqlinuxfb.so"
"/opt/SiteMonster/PyQt5/Qt/plugins/platforms/libqminimal.so"
"/opt/SiteMonster/PyQt5/Qt/plugins/platforms/libqminimalegl.so"
"/opt/SiteMonster/PyQt5/Qt/plugins/platforms/libqoffscreen.so"
"/opt/SiteMonster/PyQt5/Qt/plugins/platforms/libqvnc.so"
"/opt/SiteMonster/PyQt5/Qt/plugins/platforms/libqwayland-egl.so"
"/opt/SiteMonster/PyQt5/Qt/plugins/platforms/libqwayland-generic.so"
"/opt/SiteMonster/PyQt5/Qt/plugins/platforms/libqwayland-xcomposite-egl.so"
"/opt/SiteMonster/PyQt5/Qt/plugins/platforms/libqwayland-xcomposite-glx.so"
"/opt/SiteMonster/PyQt5/Qt/plugins/platforms/libqxcb.so"
%dir "/opt/SiteMonster/PyQt5/Qt/plugins/platformthemes/"
"/opt/SiteMonster/PyQt5/Qt/plugins/platformthemes/KDEPlasmaPlatformTheme.so"
"/opt/SiteMonster/PyQt5/Qt/plugins/platformthemes/libqgtk3.so"
%dir "/opt/SiteMonster/PyQt5/Qt/plugins/printsupport/"
"/opt/SiteMonster/PyQt5/Qt/plugins/printsupport/libcupsprintersupport.so"
"/opt/SiteMonster/PyQt5.Qt.so"
"/opt/SiteMonster/PyQt5.QtCore.so"
"/opt/SiteMonster/PyQt5.QtGui.so"
"/opt/SiteMonster/PyQt5.QtPrintSupport.so"
"/opt/SiteMonster/PyQt5.QtWidgets.so"
"/opt/SiteMonster/_bz2.so"
"/opt/SiteMonster/_cffi_backend.so"
"/opt/SiteMonster/_codecs_cn.so"
"/opt/SiteMonster/_codecs_hk.so"
"/opt/SiteMonster/_codecs_iso2022.so"
"/opt/SiteMonster/_codecs_jp.so"
"/opt/SiteMonster/_codecs_kr.so"
"/opt/SiteMonster/_codecs_tw.so"
"/opt/SiteMonster/_ctypes.so"
"/opt/SiteMonster/_decimal.so"
"/opt/SiteMonster/_hashlib.so"
"/opt/SiteMonster/_json.so"
"/opt/SiteMonster/_lzma.so"
"/opt/SiteMonster/_multibytecodec.so"
"/opt/SiteMonster/_opcode.so"
"/opt/SiteMonster/_portaudio.cpython-36m-x86_64-linux-gnu.so"
"/opt/SiteMonster/_ssl.so"
"/opt/SiteMonster/audioop.so"
"/opt/SiteMonster/base_library.zip"
%dir "/opt/SiteMonster/certifi/"
"/opt/SiteMonster/certifi/cacert.pem"
%dir "/opt/SiteMonster/cryptography-2.1.4-py3.6.egg-info/"
"/opt/SiteMonster/cryptography-2.1.4-py3.6.egg-info/PKG-INFO"
"/opt/SiteMonster/cryptography-2.1.4-py3.6.egg-info/dependency_links.txt"
"/opt/SiteMonster/cryptography-2.1.4-py3.6.egg-info/not-zip-safe"
"/opt/SiteMonster/cryptography-2.1.4-py3.6.egg-info/requires.txt"
"/opt/SiteMonster/cryptography-2.1.4-py3.6.egg-info/top_level.txt"
"/opt/SiteMonster/cryptography.hazmat.bindings._constant_time.so"
"/opt/SiteMonster/cryptography.hazmat.bindings._openssl.so"
"/opt/SiteMonster/daemon"
"/opt/SiteMonster/libEGL.so.1"
"/opt/SiteMonster/libFLAC.so.8"
"/opt/SiteMonster/libGLX.so.0"
"/opt/SiteMonster/libGLdispatch.so.0"
"/opt/SiteMonster/libHalf.so.12"
"/opt/SiteMonster/libICE.so.6"
"/opt/SiteMonster/libIex-2_2.so.12"
"/opt/SiteMonster/libIlmImf-2_2.so.22"
"/opt/SiteMonster/libIlmThread-2_2.so.12"
"/opt/SiteMonster/libKF5Archive.so.5"
"/opt/SiteMonster/libKF5Attica.so.5"
"/opt/SiteMonster/libKF5Auth.so.5"
"/opt/SiteMonster/libKF5Bookmarks.so.5"
"/opt/SiteMonster/libKF5Codecs.so.5"
"/opt/SiteMonster/libKF5Completion.so.5"
"/opt/SiteMonster/libKF5ConfigCore.so.5"
"/opt/SiteMonster/libKF5ConfigGui.so.5"
"/opt/SiteMonster/libKF5ConfigWidgets.so.5"
"/opt/SiteMonster/libKF5CoreAddons.so.5"
"/opt/SiteMonster/libKF5DBusAddons.so.5"
"/opt/SiteMonster/libKF5GlobalAccel.so.5"
"/opt/SiteMonster/libKF5GuiAddons.so.5"
"/opt/SiteMonster/libKF5I18n.so.5"
"/opt/SiteMonster/libKF5IconThemes.so.5"
"/opt/SiteMonster/libKF5ItemViews.so.5"
"/opt/SiteMonster/libKF5JobWidgets.so.5"
"/opt/SiteMonster/libKF5KIOCore.so.5"
"/opt/SiteMonster/libKF5KIOFileWidgets.so.5"
"/opt/SiteMonster/libKF5KIOWidgets.so.5"
"/opt/SiteMonster/libKF5Notifications.so.5"
"/opt/SiteMonster/libKF5Service.so.5"
"/opt/SiteMonster/libKF5Solid.so.5"
"/opt/SiteMonster/libKF5SonnetCore.so.5"
"/opt/SiteMonster/libKF5SonnetUi.so.5"
"/opt/SiteMonster/libKF5TextWidgets.so.5"
"/opt/SiteMonster/libKF5WaylandClient.so.5"
"/opt/SiteMonster/libKF5WidgetsAddons.so.5"
"/opt/SiteMonster/libKF5WindowSystem.so.5"
"/opt/SiteMonster/libKF5XmlGui.so.5"
"/opt/SiteMonster/libQt5Core.so.5"
"/opt/SiteMonster/libQt5DBus.so.5"
"/opt/SiteMonster/libQt5EglFSDeviceIntegration.so.5"
"/opt/SiteMonster/libQt5Gui.so.5"
"/opt/SiteMonster/libQt5Network.so.5"
"/opt/SiteMonster/libQt5PrintSupport.so.5"
"/opt/SiteMonster/libQt5Qml.so.5"
"/opt/SiteMonster/libQt5Quick.so.5"
"/opt/SiteMonster/libQt5QuickControls2.so.5"
"/opt/SiteMonster/libQt5QuickTemplates2.so.5"
"/opt/SiteMonster/libQt5Svg.so.5"
"/opt/SiteMonster/libQt5TextToSpeech.so.5"
"/opt/SiteMonster/libQt5WaylandClient.so.5"
"/opt/SiteMonster/libQt5Widgets.so.5"
"/opt/SiteMonster/libQt5X11Extras.so.5"
"/opt/SiteMonster/libQt5XcbQpa.so.5"
"/opt/SiteMonster/libQt5Xml.so.5"
"/opt/SiteMonster/libSM.so.6"
"/opt/SiteMonster/libX11-xcb.so.1"
"/opt/SiteMonster/libX11.so.6"
"/opt/SiteMonster/libXau.so.6"
"/opt/SiteMonster/libXcomposite.so.1"
"/opt/SiteMonster/libXcursor.so.1"
"/opt/SiteMonster/libXdamage.so.1"
"/opt/SiteMonster/libXdmcp.so.6"
"/opt/SiteMonster/libXext.so.6"
"/opt/SiteMonster/libXfixes.so.3"
"/opt/SiteMonster/libXi.so.6"
"/opt/SiteMonster/libXinerama.so.1"
"/opt/SiteMonster/libXrandr.so.2"
"/opt/SiteMonster/libXrender.so.1"
"/opt/SiteMonster/libacl.so.1"
"/opt/SiteMonster/libasyncns.so.0"
"/opt/SiteMonster/libatk-1.0.so.0"
"/opt/SiteMonster/libatk-bridge-2.0.so.0"
"/opt/SiteMonster/libatspi.so.0"
"/opt/SiteMonster/libattr.so.1"
"/opt/SiteMonster/libavahi-client.so.3"
"/opt/SiteMonster/libavahi-common.so.3"
"/opt/SiteMonster/libblkid.so.1"
"/opt/SiteMonster/libbsd.so.0"
"/opt/SiteMonster/libbz2.so.1.0"
"/opt/SiteMonster/libcairo-gobject.so.2"
"/opt/SiteMonster/libcairo.so.2"
"/opt/SiteMonster/libcom_err.so.2"
"/opt/SiteMonster/libcrypto.so.1.1"
"/opt/SiteMonster/libcups.so.2"
"/opt/SiteMonster/libdatrie.so.1"
"/opt/SiteMonster/libdbus-1.so.3"
"/opt/SiteMonster/libdbusmenu-qt5.so.2"
"/opt/SiteMonster/libdouble-conversion.so.1"
"/opt/SiteMonster/libdrm.so.2"
"/opt/SiteMonster/libepoxy.so.0"
"/opt/SiteMonster/libevdev.so.2"
"/opt/SiteMonster/libexpat.so.1"
"/opt/SiteMonster/libfam.so.0"
"/opt/SiteMonster/libffi.so.6"
"/opt/SiteMonster/libfontconfig.so.1"
"/opt/SiteMonster/libfreetype.so.6"
"/opt/SiteMonster/libgcc_s.so.1"
"/opt/SiteMonster/libgcrypt.so.20"
"/opt/SiteMonster/libgdk-3.so.0"
"/opt/SiteMonster/libgdk_pixbuf-2.0.so.0"
"/opt/SiteMonster/libgio-2.0.so.0"
"/opt/SiteMonster/libglib-2.0.so.0"
"/opt/SiteMonster/libgmodule-2.0.so.0"
"/opt/SiteMonster/libgmp.so.10"
"/opt/SiteMonster/libgnutls.so.30"
"/opt/SiteMonster/libgobject-2.0.so.0"
"/opt/SiteMonster/libgpg-error.so.0"
"/opt/SiteMonster/libgraphite2.so.3"
"/opt/SiteMonster/libgssapi_krb5.so.2"
"/opt/SiteMonster/libgtk-3.so.0"
"/opt/SiteMonster/libgudev-1.0.so.0"
"/opt/SiteMonster/libharfbuzz.so.0"
"/opt/SiteMonster/libhogweed.so.4"
"/opt/SiteMonster/libicudata.so.60"
"/opt/SiteMonster/libicui18n.so.60"
"/opt/SiteMonster/libicuuc.so.60"
"/opt/SiteMonster/libidn2.so.0"
"/opt/SiteMonster/libinput.so.10"
"/opt/SiteMonster/libjbig.so.0"
"/opt/SiteMonster/libjpeg.so.8"
"/opt/SiteMonster/libk5crypto.so.3"
"/opt/SiteMonster/libkeyutils.so.1"
"/opt/SiteMonster/libkrb5.so.3"
"/opt/SiteMonster/libkrb5support.so.0"
"/opt/SiteMonster/liblcms2.so.2"
"/opt/SiteMonster/liblz4.so.1"
"/opt/SiteMonster/liblzma.so.5"
"/opt/SiteMonster/libmng.so.2"
"/opt/SiteMonster/libmount.so.1"
"/opt/SiteMonster/libmpdec.so.2"
"/opt/SiteMonster/libmtdev.so.1"
"/opt/SiteMonster/libnettle.so.6"
"/opt/SiteMonster/libogg.so.0"
"/opt/SiteMonster/libp11-kit.so.0"
"/opt/SiteMonster/libpango-1.0.so.0"
"/opt/SiteMonster/libpangocairo-1.0.so.0"
"/opt/SiteMonster/libpangoft2-1.0.so.0"
"/opt/SiteMonster/libpcre.so.3"
"/opt/SiteMonster/libphonon4qt5.so.4"
"/opt/SiteMonster/libpixman-1.so.0"
"/opt/SiteMonster/libpng16.so.16"
"/opt/SiteMonster/libpulse-mainloop-glib.so.0"
"/opt/SiteMonster/libpulse.so.0"
"/opt/SiteMonster/libpulsecommon-11.1.so"
"/opt/SiteMonster/libpython3.6m.so.1.0"
"/opt/SiteMonster/libreadline.so.7"
"/opt/SiteMonster/libselinux.so.1"
"/opt/SiteMonster/libsndfile.so.1"
"/opt/SiteMonster/libssl.so.1.1"
"/opt/SiteMonster/libstdc++.so.6"
"/opt/SiteMonster/libsystemd.so.0"
"/opt/SiteMonster/libtasn1.so.6"
"/opt/SiteMonster/libthai.so.0"
"/opt/SiteMonster/libtiff.so.5"
"/opt/SiteMonster/libtinfo.so.5"
"/opt/SiteMonster/libudev.so.1"
"/opt/SiteMonster/libunistring.so.2"
"/opt/SiteMonster/libuuid.so.1"
"/opt/SiteMonster/libvorbis.so.0"
"/opt/SiteMonster/libvorbisenc.so.2"
"/opt/SiteMonster/libwacom.so.2"
"/opt/SiteMonster/libwayland-client.so.0"
"/opt/SiteMonster/libwayland-cursor.so.0"
"/opt/SiteMonster/libwayland-egl.so.1"
"/opt/SiteMonster/libwebp.so.6"
"/opt/SiteMonster/libwebpdemux.so.2"
"/opt/SiteMonster/libwrap.so.0"
"/opt/SiteMonster/libxcb-icccm.so.4"
"/opt/SiteMonster/libxcb-image.so.0"
"/opt/SiteMonster/libxcb-keysyms.so.1"
"/opt/SiteMonster/libxcb-randr.so.0"
"/opt/SiteMonster/libxcb-render-util.so.0"
"/opt/SiteMonster/libxcb-render.so.0"
"/opt/SiteMonster/libxcb-shape.so.0"
"/opt/SiteMonster/libxcb-shm.so.0"
"/opt/SiteMonster/libxcb-sync.so.1"
"/opt/SiteMonster/libxcb-util.so.1"
"/opt/SiteMonster/libxcb-xfixes.so.0"
"/opt/SiteMonster/libxcb-xinerama.so.0"
"/opt/SiteMonster/libxcb-xkb.so.1"
"/opt/SiteMonster/libxkbcommon-x11.so.0"
"/opt/SiteMonster/libxkbcommon.so.0"
"/opt/SiteMonster/libz.so.1"
%dir "/opt/SiteMonster/main/"
%dir "/opt/SiteMonster/media/"
"/opt/SiteMonster/media/SegoeUI.ttf"
"/opt/SiteMonster/media/alarm.wav"
"/opt/SiteMonster/media/back.png"
"/opt/SiteMonster/media/checkbox-off-hover.png"
"/opt/SiteMonster/media/checkbox-off-pressed.png"
"/opt/SiteMonster/media/checkbox-off.png"
"/opt/SiteMonster/media/checkbox-on-hover.png"
"/opt/SiteMonster/media/checkbox-on-pressed.png"
"/opt/SiteMonster/media/checkbox-on.png"
"/opt/SiteMonster/media/filter.png"
"/opt/SiteMonster/media/logo.ico"
"/opt/SiteMonster/media/menu.png"
"/opt/SiteMonster/media/plus.png"
"/opt/SiteMonster/media/settings.png"
"/opt/SiteMonster/media/star-off-hover.png"
"/opt/SiteMonster/media/star-off-pressed.png"
"/opt/SiteMonster/media/star-off.png"
"/opt/SiteMonster/media/star-on-hover.png"
"/opt/SiteMonster/media/star-on-pressed.png"
"/opt/SiteMonster/media/star-on.png"
"/opt/SiteMonster/media/trash.png"
"/opt/SiteMonster/psutil._psutil_linux.so"
"/opt/SiteMonster/psutil._psutil_posix.so"
"/opt/SiteMonster/readline.so"
"/opt/SiteMonster/resource.so"
"/opt/SiteMonster/sip.so"
"/opt/SiteMonster/sitemonster"
"/opt/SiteMonster/termios.so"
"/opt/SiteMonster/updater"
%dir "/usr/"
%dir "/usr/share/"
%dir "/usr/share/applications/"
"/usr/share/applications/Site Monster.desktop"
"/usr/share/applications/daemon.desktop"
